version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.10"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Setup build system
          command: mkdir build;cd build;cmake ..
      - run:
          name: Build project
          command: cd build;make -j4
